{
 "title": "Sample Monitorable Application",
 "description": "Đây là ví dụ mà mình sẽ sử dụng Grafana + Prometheus vào trong một ứng dụng mẫu, để demo phần Monitoring.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Concurrent Requests",
   "type": "bargauge",
   "description": "Biểu đồ cho thấy số lượng requests đồng thời được gửi và xử lý bởi server.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_concurrent_requests{route=~\"/sample/.*\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (P90)",
   "type": "timeseries",
   "description": "Biểu đồ cho biết biến động của Request Latency. Con số càng cao thì hệ thống đang gặp vấn đề.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Request of Sample Routes",
   "type": "timeseries",
   "description": "Biểu đồ thể hiện sự tổng các requests tới sample routes qua thời gian",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"sma\", route=~\"/sample/.*\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Increment rate of sample routes request (1m)",
   "type": "timeseries",
   "description": "Biểu đồ thể hiện tốc độ gia tăng requests trung bình của sample routes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"sma\", route=~\"/sample/.*\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total of successful requests (2xx-3xx)",
   "type": "timeseries",
   "description": "Biểu đồ thể hiện tổng các request thành công (2xx-3xx)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "http_requests_statuscode_total{status_code=~\"2..\"}",
     "legendFormat": "{{status_code}}"
    },
    {
     "expr": "http_requests_statuscode_total{status_code=~\"3..\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Increment rate of successful requests (2xx-3xx)",
   "type": "timeseries",
   "description": "Biểu đồ thể hiện tốc độ tăng trung bình của các request thành công trong mỗi phút",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(http_requests_statuscode_total{status_code=~\"2..\"}[1m])",
     "legendFormat": "{{status_code}}"
    },
    {
     "expr": "rate(http_requests_statuscode_total{status_code=~\"3..\"}[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total of error / failed requests (4xx-5xx)",
   "type": "timeseries",
   "description": "Biểu đồ thể hiện tổng các request lỗi / thất bại (4xx-5xx)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "http_requests_statuscode_total{status_code=~\"4..\"}",
     "legendFormat": "{{status_code}}"
    },
    {
     "expr": "http_requests_statuscode_total{status_code=~\"5..\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Increment rate of error / failed requests (2xx-3xx)",
   "type": "timeseries",
   "description": "Biểu đồ thể hiện tốc độ tăng trung bình của các request lỗi / thất bại trong mỗi phút",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(http_requests_statuscode_total{status_code=~\"4..\"}[1m])",
     "legendFormat": "{{status_code}}"
    },
    {
     "expr": "rate(http_requests_statuscode_total{status_code=~\"5..\"}[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}